---
  title: "PD1 percentage"
---
  
```{r}
library(tidyverse)
library(Seurat)

labels<-data.table::fread("/media/Lawrenson_Lab_NAS/uthscsa/group_data/Xenium_labels/pembro/Banksy_matrix/prote_l0.2_labels.gz")
labels<-labels%>%mutate(m1_cl=case_when(m1_cl%in%c(1:4,"Dendritic Cells")~"Macrophages M2",
                                        m1_cl==5~"Dendritic cells",TRUE~m1_cl))
labels<-labels%>%mutate(c7_cl=case_when(c7_cl==1~"Mesenchymal cells",
                                        c7_cl%in%c(2,4)~"Activated Fibro/CAF",
                                        c7_cl==3~"C7-Activated Fibro",
                                        c7_cl==5~"C7-Fibro",
                                        c7_cl==6~"Activated Fibro",TRUE~m1_cl))
labels<-labels%>%filter(str_detect(c7_cl,"disc",negate = T))%>%
  mutate(finalabel=str_remove(c7_cl,"Effector "))
labels<-labels%>%mutate(toplabel=case_when(str_detect(finalabel,"^B|Pla")~"B_Plasma",
                                           str_detect(finalabel,"Fib|Mes|Smo")~"Mesenchymal",
                                           str_detect(finalabel,"CD8")~"CD8 T-cells",
                                           str_detect(finalabel,"Macr|Dend")~"Myeloid",
                                           finalabel=="NK cells"~"Gamma_NK",TRUE~finalabel))

coords<-data.table::fread("/media/Lawrenson_Lab_NAS/uthscsa/group_data/Xenium_labels/pembro/Banksy_domains.gz")
meta<-coords%>%select(cell_id,x_centroid,y_centroid,circle,Core_ID)%>%inner_join(labels)

```

# Load expression data
```{r}
files<-list.files("/media/Xenium_On_NAS/xenium_reanalysis",full.names = T)
files<-files[str_detect(files,"Pro")]
files<-files[str_detect(files,"UTP",negate=T)]
xenium.list<-lapply(files, function(x) Read10X_h5(paste0(x,"/outs/cell_feature_matrix.h5")))
prote.list<-lapply(xenium.list,function(x) x$`Protein Expression`)
names(xenium.list)<-str_remove(files,".+sis.")
names(prote.list)<-str_remove(files,".+sis.")

prote.list<-lapply(prote.list,function(x) CreateSeuratObject(counts = x))
inteP<-merge(prote.list[[1]],y = prote.list[names(prote.list)[-1]],
            add.cell.ids =names(prote.list))
inteP<-subset(inteP,cells=meta$cell_id)
meta<-meta[order(match(meta$cell_id,colnames(inteP))),]
inteP<-AddMetaData(inteP,metadata = meta%>%column_to_rownames("cell_id"))
rm(prote.list)

inteP<-NormalizeData(inteP)
#inteP<-ScaleData(inteP,features = rownames(inteP))
#inteP<-RunPCA(inteP,features = rownames(inteP))
#inteP<-IntegrateLayers(inteP,method = "HarmonyIntegration",features = rownames(inteP))
inteP<-JoinLayers(inteP)

```

# Summary matrix
```{r}

temp<-inteP@assays$RNA$data
temp<-temp%>%t()%>%as.data.frame()%>%rownames_to_column("cell_id")%>%
  inner_join(meta)
temp1<-temp%>%group_by(finalabel)%>%summarise(across(c(`PD-1`,`PD-L1`,CD45,PanCK,alphaSMA),mean))
i<-temp1%>%pivot_longer(-1,names_to = "protein",values_to = "avg")%>%group_by(protein)%>%slice_max(avg)
i<-temp%>%select(finalabel,`PD-1`,`PD-L1`,CD45,PanCK,alphaSMA)%>%
  pivot_longer(-1,names_to = "protein",values_to = "val")%>%
  inner_join(i)%>%group_by(protein)%>%summarise(th=quantile(val,.05))%>%
  deframe
#res<-temp%>%group_by(circle,Core_ID,responder)%>%summarise(across(`PD-1`:`E-Cadherin`,function(x) sum(x>0)),total=n())
res<-temp%>%group_by(circle,Core_ID,respo)%>%
  summarise(total=n(),
            PanCKonly=sum(PanCK>i["PanCK"] & CD45<=i["CD45"]),
            PDL1_PanCK=sum(PanCK>i["PanCK"] & CD45<=i["CD45"] & `PD-L1`>i["PD-L1"]),
            CD45only=sum(CD45>i["CD45"] & PanCK<=i["PanCK"]),
            PDL1_CD45=sum(CD45>i["CD45"] & PanCK<=i["PanCK"] & `PD-L1`>i["PD-L1"]),
            PD1_CD45=sum(CD45>i["CD45"] & PanCK<=i["PanCK"] & `PD-1`>i["PD-1"]))
annot<-read_tsv("/media/Lawrenson_Lab_NAS/uthscsa/group_data/Xenium_labels/pembro/PEmbro_TMA_deidentified.tsv")
res<-res%>%mutate(Core_ID=as.numeric(Core_ID))%>%inner_join(annot,by=c("Core_ID"="Core ID"))

p0<-res%>%ggplot(aes(x=responder,y=PanCKonly/total))+geom_violin()+geom_boxplot(width=.05)
p1<-res%>%ggplot(aes(x=responder,y=PDL1_PanCK/PanCKonly))+geom_violin()+geom_boxplot(width=.1)+stat_compare_means(label="p.signif",comparisons = list(c("TRUE","FALSE")))
p2<-res%>%ggplot(aes(x=responder,y=PD1_CD45/CD45only))+geom_violin()+geom_boxplot(width=.1)+stat_compare_means(label="p.signif",comparisons = list(c("TRUE","FALSE")))
p3<-res%>%ggplot(aes(x=responder,y=(PDL1_PanCK+PDL1_CD45)/(PanCKonly+CD45only)))+geom_violin(alpha=.5)+geom_boxplot(width=.1)+stat_compare_means(label="p.signif",comparisons = list(c("TRUE","FALSE")))




```
