---
  title: "Cell composition"
output: html_notebook
---
  
  
```{r}
library(tidyverse)
library(dbscan)
library(speckle)
library(limma)
cols<-c("#E41A1C","#536D9E","#459E6E","cornflowerblue","gold","#F29022","#F781BF","#C598C9",
        "#AD6D5E","#7D8285","#4385BF","#204175","#1B9E77","#98D486","#D2C92D","#EFAC4C",
        "#F47494","#D8227D","#910241","#18ABB8","#6ECDDC","#f46d43","#A82676","#655D9B",
        "#8CA77B","#17542A","#94A908","#C8DD34","#8FC9BF","white")

labels<-data.table::fread("/media/Lawrenson_Lab_NAS/uthscsa/group_data/Xenium_labels/pembro/Banksy_matrix/prote_l0.2_labels.gz")
labels<-labels%>%mutate(m1_cl=case_when(m1_cl%in%c(1:4,"Dendritic Cells")~"Macrophages M2",
                                        m1_cl==5~"Dendritic cells",TRUE~m1_cl))
labels<-labels%>%mutate(c7_cl=case_when(c7_cl==1~"Mesenchymal cells",
                                        c7_cl%in%c(2,4)~"Activated Fibro/CAF",
                                        c7_cl==3~"C7-Activated Fibro",
                                        c7_cl==5~"C7-Fibro",
                                        c7_cl==6~"Activated Fibro",TRUE~m1_cl))
labels<-labels%>%filter(str_detect(c7_cl,"disc",negate = T))%>%
  mutate(finalabel=str_remove(c7_cl,"Effector "))
labels<-labels%>%mutate(toplabel=case_when(str_detect(finalabel,"^B|Pla")~"B_Plasma",
                                           str_detect(finalabel,"Fib|Mes|Smo")~"Mesenchymal",
                                           str_detect(finalabel,"CD8")~"CD8 T-cells",
                                           str_detect(finalabel,"Macr|Dend")~"Myeloid",
                                           finalabel=="NK cells"~"Gamma_NK",TRUE~finalabel))

files<-list.files("/media/Lawrenson_Lab_NAS/uthscsa/group_data/Xenium_labels/pembro",full.names = T)
files<-files[str_detect(files,"Prime")]
labels_5k<-lapply(files,data.table::fread)
names(labels_5k)<-str_remove_all(files,".+bro.|bnks.+")
labels_5k<-lapply(names(labels_5k),function(x) labels_5k[[x]]%>%mutate(Section=x))%>%bind_rows()
labels_5k<-labels_5k%>%mutate(cell=paste0(Section,'_',cell))
```

# Coordinates
```{r}
temp<-labels_5k%>%mutate(toplabel=str_replace(percl_toplabel,"EnS cells","Mesenchymal"),panel="5k")%>%
  select(cell,toplabel,panel)
temp<-labels%>%mutate(panel="targeted")%>%select(cell,toplabel,panel)%>%bind_rows(temp)

coords<-data.table::fread("/media/Lawrenson_Lab_NAS/uthscsa/group_data/Xenium_labels/pembro/Banksy_domains.gz")
coords5k<-data.table::fread("/media/Lawrenson_Lab_NAS/uthscsa/group_data/Xenium_labels/pembro/Banksy_domains5k.gz")
coords<-coords%>%mutate(panel="targeted")
coords<-coords5k%>%mutate(panel="5k")%>%bind_rows(coords)
temp<-coords%>%select(cell_id,x_centroid,y_centroid,circle,Core_ID)%>%inner_join(temp,by=c("cell_id"="cell"))
temp<-temp%>%add_count(panel,circle)%>%filter(n>500)

cellcols<-c(Epithelial="#F29022","CD4 T-cells"="#18ABB8","unknown"="#AD6D5E",
            "B_Plasma"="#C8DD34","Myeloid"="#F781BF",
            "Mesenchymal"="#204175","Endothelial cells"="#E41A1C",
            "CD8 T-cells"="gold","Gamma_NK" ="#910241")
plots<-lapply(unique(temp$Core_ID),function(i)
    temp%>%filter(Core_ID==i)%>%ggplot(aes(x=-x_centroid,y=-y_centroid,col=toplabel))+
      geom_point(size=.1)+facet_grid(cols=vars(panel),scales="free",space="free")+
      scale_color_manual(values=cellcols)+guides(col=guide_legend(override.aes = list(size=3)))+
     ggtitle(paste0("Core_ID=",i))+theme(legend.position = "n"))

p0<-temp%>%count(toplabel,panel)%>%ggplot(aes(x=n,y=toplabel,fill=toplabel))+
  geom_col()+geom_text(aes(label=n))+scale_fill_manual(values=cellcols)+
  theme(legend.position = "n")+facet_grid(~panel)+scale_x_log10()
```

# Contrast
```{r}
annot<-read_tsv("/media/Lawrenson_Lab_NAS/uthscsa/group_data/Xenium_labels/pembro/PEmbro_TMA_deidentified.tsv")
temp<-temp%>%mutate(Core_ID=as.numeric(Core_ID))%>%left_join(annot,by = c("Core_ID"="Core ID"))

temp<-temp%>%mutate(Gr=ifelse(responder==T,"responder","non_responder"))
run_speckle<-function(metadata){
  props<-getTransformedProps(metadata$toplabel,
                             metadata$StudyID)
  ids<-metadata%>%distinct(Gr,StudyID)
  designM<-model.matrix(~0+Gr,data=ids)#but Cores are not independent 
  
  props<-props$TransformedProps[,ids$StudyID]
  fit<-lmFit(props,designM)
  cont<-makeContrasts(Grresponder-Grnon_responder,levels = designM)
  fit<-contrasts.fit(fit,cont)
  fit <- eBayes(fit, robust=TRUE)
  res<-topTable(fit,number = nrow(props),coef = 1)
  return(res)}
proteinres<-temp%>%filter(panel=="targeted")%>%run_speckle()
res5k<-temp%>%filter(panel=="5k")%>%run_speckle()

toplot<-proteinres%>%rownames_to_column("ct")%>%
  mutate(targetedLFC=logFC)%>%select(ct,targetedLFC)
toplot<-res5k%>%rownames_to_column("ct")%>%
  mutate(LFC5k=logFC)%>%select(ct,LFC5k)%>%inner_join(toplot)
toplot%>%ggplot(aes(x=targetedLFC,y=LFC5k))+
  geom_point(aes(col=ct,label=ct),size=3)+
  geom_text_repel(aes(col=ct,label=ct))+
  scale_color_manual(values=cols)+
  geom_smooth(method = "lm")
```

# Verify markers
## 5k
```{r}
files<-list.files("/media/Xenium_On_NAS/xenium_reanalysis",full.names = T)
files<-files[str_detect(files,"TMA")]
files<-files[str_detect(files,"Prime")]
files<-files[str_detect(files,"UTP",negate = T)]

xenium.list<-lapply(files, function(x) Read10X_h5(paste0(x,"/outs/cell_feature_matrix.h5")))
names(xenium.list)<-str_remove(files,".+sis.")
xenium.list<-lapply(xenium.list,function(x) x$`Gene Expression`)
xenium.list<-lapply(xenium.list,function(x) CreateSeuratObject(counts = x))
inte<-merge(xenium.list[[1]],y = xenium.list[names(xenium.list)[-1]],
            add.cell.ids =names(xenium.list))
rm(xenium.list)

inte<-subset(inte,cells = labels$cell_id)
temp<-labels%>%filter(cell_id%in%colnames(inte))
temp<-temp[order(match(temp$cell_id,colnames(inte))),]
inte<-AddMetaData(inte,metadata = temp%>%column_to_rownames("cell_id"),col.name = "percl_toplabel")

j<-c("KIT","TPSAB1","SIGLEC8","PTPRC","CD79A","BANK1","MS4A1",
     "CD27","CD38","BCL6","CXCR5","MME","JCHAIN","PRDM1","SDC1",
     "IGHA1","IGHG1","IGHG2","IGHG3","IGHG4","IGHM","NCAM1","FCGR3A",
     "CD3D","TRDC","TRGC1","TRGC2","CD4","IL4","GATA3","CCR4","CXCR4",
     "RORC","IL17A","STAT3","CCR6","FOXP3","IL2RA","CD8A","SELL",
     "CCR7","CD44","IL7R","CD69","CTLA4","LAG3","PDCD1","TIGIT","HAVCR2",
     "TOX","CD1C","HLA-DRA","HLA-DPA1","ITGAM","CD68","CXCL10","CCL2",
     "NOS2","ARG1","CD163","IL10","EPCAM","KRT10","KRT18","KRT8","WT1",
     "MUC5B","SOX9","SPDEF","LGR5",
     "PAX8","ESR1","FOXJ1","PAEP","PECAM1","PGR","IGF1","MMP11","FOXO1",
     "DCN","PDGFRA","THY1","COL1A1","ACTA2","TAGLN","MYL9","FAP","C7","GAS5")
DotPlot(inte,group.by = "percl_toplabel",features = j)+
  scale_color_gradient2(low="#2166ac", mid = "#f7f7f7", high = "#b2182b")+
  theme(axis.text.x = element_text(angle=45,vjust = 1,hjust = 1))

```

# Domain composition
```{r}
labels<-labels%>%inner_join(coords,by=c("cell"="cell_id"))
labels<-labels%>%mutate(Core_ID=as.numeric(Core_ID))%>%
  left_join(annot,by = c("Core_ID"="Core ID"))

toplot<-labels%>%count(res.0.5,responder)%>%
  group_by(res.0.5)%>%mutate(prop=n/sum(n))%>%arrange(prop)
p0<-toplot%>%mutate(res.0.5=factor(res.0.5,
                                   levels=toplot%>%filter(responder==T)%>%
                                     select(res.0.5)%>%unlist()))%>%
  ggplot(aes(x=res.0.5,y = n,fill=responder))+
  geom_bar(stat="identity",position="fill")
p1<-labels%>%distinct(res.0.5,StudyID)%>%count(res.0.5)%>%
  mutate(res.0.5=factor(res.0.5,levels=levels(p0$data$res.0.5)))%>%
  ggplot(aes(x=res.0.5,y=n))+geom_col()+labs(y="StudyID")
p2<-labels%>%count(res.0.5,toplabel)%>%
  mutate(res.0.5=factor(res.0.5,levels=levels(p0$data$res.0.5)))%>%
  ggplot(aes(x=res.0.5,y = n,fill=toplabel))+
  geom_bar(stat="identity",position="fill")+
  scale_fill_manual(values = cellcols)

```

# PD1 in D14?
```{r}
files<-list.files("/media/Xenium_On_NAS/xenium_reanalysis",full.names = T)
files<-files[str_detect(files,"Pro")]
files<-files[str_detect(files,"UTP",negate=T)]
xenium.list<-lapply(files, function(x) Read10X_h5(paste0(x,"/outs/cell_feature_matrix.h5")))
names(xenium.list)<-str_remove(files,".+sis.")

prote.list<-lapply(xenium.list,function(x) x$`Protein Expression`)
inteP<-lapply(prote.list, CreateSeuratObject)
inteP<-merge(inteP[[1]],y = inteP[names(inteP)[-1]],
             add.cell.ids =names(inteP))
inteP<-subset(inteP,cell = labels$cell)
#sum(colnames(inteP)==rownames(clus))
inteP<-AddMetaData(inteP,metadata = labels%>%column_to_rownames("cell"))
inteP<-NormalizeData(inteP) #CLR???
inteP<-ScaleData(inteP)

DotPlot(subset(inteP,subset = finalabel%in%c("Exhausted CD8 T-cells","CD8 T-cells")),
        group.by = "res.0.5",features = c("PD-1","PD-L1"))+
  scale_color_gradient2(low="#2166ac", mid = "#f7f7f7", high = "#b2182b")+
  ggtitle("All CD8 T-cells")+labs(y="Domain")
DotPlot(inteP,group.by = "res.0.5",features = c("PD-1","PD-L1"))+
  scale_color_gradient2(low="#2166ac", mid = "#f7f7f7", high = "#b2182b")+
  ggtitle("All cells")+labs(y="Domain")
```
