---
  title: "domains"
---
  
```{r}
library(tidyverse)
library(Seurat)
library(Banksy)
library(SeuratWrappers)
library(SingleR)
cols<-c("#E41A1C","#536D9E","#459E6E","cornflowerblue","gold","#F29022","#F781BF","#C598C9",
        "#AD6D5E","#7D8285","#4385BF","#204175","#1B9E77","#98D486","#D2C92D","#EFAC4C",
        "#F47494","#D8227D","#910241","#18ABB8","#6ECDDC","#f46d43","#A82676","#655D9B",
        "#8CA77B","#17542A","#94A908","#C8DD34","#8FC9BF","white")

meta<-data.table::fread("/media/Lawrenson_Lab_NAS/uthscsa/group_data/Xenium_labels/pembro/Banksy_domains.gz")
meta<-meta%>%add_count(circle)%>%filter(n>500)
temp<-read_tsv("/media/Lawrenson_Lab_NAS/uthscsa/group_data/Xenium_labels/pembro/PEmbro_TMA_deidentified.tsv")
meta<-meta%>%mutate(Core_ID=as.numeric(Core_ID))%>%left_join(temp,by=c("Core_ID"="Core ID"))
```

# Main cell type
```{r}
files<-list.files("/media/Xenium_On_NAS/xenium_reanalysis",full.names = T)
files<-files[str_detect(files,"Pro")]
files<-files[str_detect(files,"UTP",negate=T)]
xenium.list<-lapply(files, function(x) Read10X_h5(paste0(x,"/outs/cell_feature_matrix.h5")))
names(xenium.list)<-str_remove(files,".+sis.")

prote.list<-lapply(xenium.list,function(x) x$`Protein Expression`)
inteP<-lapply(prote.list, CreateSeuratObject)
inteP<-merge(inteP[[1]],y = inteP[names(inteP)[-1]],
            add.cell.ids =names(inteP))
inteP<-subset(inteP,cells=meta$cell_id)
#sum(colnames(inteP)==rownames(clus))
inteP<-AddMetaData(inteP,metadata = meta%>%column_to_rownames("cell_id"))
inteP<-NormalizeData(inteP)
inteP<-ScaleData(inteP)
#inteP<-RunPCA(inteP,features = rownames(inteP)) not needed for Banksy
#inteP<-IntegrateLayers(inteP,method = HarmonyIntegration,features = rownames(inteP)) #not needed for Banksy
inteP<-JoinLayers(inteP)

set.seed(1000) 
inteP@assays$RNA$data<-as.matrix(inteP@assays$RNA$data)
inteP <- RunBanksy(inteP, lambda = .2, verbose=TRUE, 
                assay = 'RNA',features = "all",
                use_agf=T,dimx = "x_centroid",dimy = "y_centroid")
mat<-inteP@assays$BANKSY$data
mat%>%t()%>%as.data.frame()%>%rownames_to_column("cell")%>%data.table::fwrite("/media/Lawrenson_Lab_NAS/uthscsa/group_data/Xenium_labels/pembro/Banksy_matrix/prote_l0.2_bnksy_mtrx.gz")
pcres<-irlba::irlba(A = t(mat),nv=50)
hares<-harmony::RunHarmony(pcres$u,meta_data=meta$circle)

rownames(hares)<-colnames(mat)
colnames(hares)<-paste0("pc",1:50)
neighs<-FindNeighbors(hares,k.param = 50)
clus<-FindClusters(neighs$snn, resolution = 0.05,algorithm = 4)
inteP@meta.data$ct_res0.05<-clus$res.0.05
p0<-DotPlot(inteP,group.by = "ct_res0.05",features = rownames(inteP))+
  coord_flip()+scale_color_gradient2(low="#2166ac", mid = "#f7f7f7", high = "#b2182b")

i<-inteP@meta.data%>%filter(ct_res0.05%in%c(2,3))%>%rownames()
subn<-neighs$snn[i,i]
clus<-FindClusters(subn, resolution = 0.1,algorithm = 4)
temp<-inteP@meta.data%>%rownames_to_column("cell")%>%select(cell,ct_res0.05)
temp<-clus%>%rownames_to_column("cell")%>%
  mutate(ct_subres0.1=res.0.1)%>%
  select(cell,ct_subres0.1)%>%right_join(temp)
temp<-temp%>%mutate(ct=ifelse(cell%in%i,10+as.numeric(ct_subres0.1),ct_res0.05))
temp<-temp[order(match(temp$cell,colnames(inteP))),]
tem%>%data.table::fwrite("/media/Lawrenson_Lab_NAS/uthscsa/group_data/Xenium_labels/pembro/Banksy_matrix/prote_l0.2_cls.gz")
inteP<-AddMetaData(inteP,metadata = temp,col.name = "ct")
p1<-DotPlot(inteP,group.by = "ct",features = rownames(inteP))+
    coord_flip()+scale_color_gradient2(low="#2166ac", mid = "#f7f7f7", high = "#b2182b")

umap_results <- uwot::umap(hares)
umap_results<-as.data.frame(umap_results)
colnames(umap_results)<-c("UMAP1","UMAP2")
umap_results$ct<-temp$ct
p2<-umap_results%>%ggplot(aes(x=UMAP1,y=UMAP2,col=ct))+geom_point(size=.1)+
  guides(col=guide_legend(override.aes = list(size=3)))
```

# Subtypes
```{r}
gene.list<-lapply(xenium.list,function(x) x$`Gene Expression`)
inte<-lapply(gene.list, CreateSeuratObject)
inte<-merge(inte[[1]],y = inte[names(inte)[-1]],
            add.cell.ids =names(inte))
inte<-subset(inte,cells=meta$cell_id)
#sum(colnames(inteP)==rownames(clus))
inte<-AddMetaData(inte,metadata = meta%>%column_to_rownames("cell_id"))
inte<-NormalizeData(inte)
i<-rownames(inte)
i<-i[str_detect(i,"bact|fung",negate = T)]
inte<-subset(inte,features = i)
inte<-ScaleData(inte)
#inte<-IntegrateLayers(inte,method = HarmonyIntegration,features = i)
inte<-JoinLayers(inte)

set.seed(1000) 
inte@assays$RNA$data<-as.matrix(inte@assays$RNA$data)
inte <- RunBanksy(inte, lambda = .2, verbose=TRUE, 
                assay = 'RNA',features = "all",
                use_agf=T,dimx = "x_centroid",dimy = "y_centroid")
mat<-inte@assays$BANKSY$data
mat%>%t()%>%as.data.frame()%>%rownames_to_column("cell")%>%data.table::fwrite("/media/Lawrenson_Lab_NAS/uthscsa/group_data/Xenium_labels/pembro/Banksy_matrix/GE_l0.2_bnksy_mtrx.gz")

protecl<-inteP@meta.data%>%rownames_to_column("cell")%>%select(cell,ct_res0.05,ct)
i<-protecl%>%filter(ct%in%c(11,13:18))%>%distinct(cell)%>%unlist()
pcres<-irlba::irlba(A = t(mat[,i]),nv=10)
hares<-harmony::RunHarmony(pcres$u,meta_data=meta$circle[meta$cell_id%in%i])
rownames(hares)<-i
colnames(hares)<-paste0("pc",1:10)
neighsE<-FindNeighbors(hares,k.param = 30)
immune_clus<-FindClusters(neighsE$snn,
                          initial.membership = protecl$ct[protecl$cell%in%i],
                          resolution = .8,method = 4)

i<-protecl%>%filter(ct==12)%>%distinct(cell)%>%unlist()
pcres<-irlba::irlba(A = t(mat[,i]),nv=10)
hares<-harmony::RunHarmony(pcres$u,meta_data=meta$circle[meta$cell_id%in%i])
rownames(hares)<-i
colnames(hares)<-paste0("pc",1:10)
neighsE<-FindNeighbors(hares,k.param = 30)
mesen_clus<-FindClusters(neighsE$snn,
                          initial.membership = protecl$ct[protecl$cell%in%i],
                          resolution = .1,method = 4)

temp<-immune_clus%>%rownames_to_column("cell")%>%
  mutate(ct=paste0("immune_",res.0.8))%>%select(cell,ct)
temp<-mesen_clus%>%rownames_to_column("cell")%>%
  mutate(ct=paste0("mesenchymal_",res.0.1))%>%select(cell,ct)%>%bind_rows(temp)
temp<-protecl%>%filter(!cell%in%temp$cell)%>%
  mutate(ct=paste0("protein_",ct))%>%select(cell,ct)%>%bind_rows(temp)
temp<-temp[order(match(temp$cell,colnames(inte))),]
inte@meta.data$ct<-temp$ct
```

# SingleR
```{r}
bulkref<-readRDS("/media/Lawrenson_Lab_NAS/uthscsa/group_data/Xenium_labels/bulkref.RDS")
bulkref<-subset(bulkref,subset=label!="Erythrocytes")
bulkref@meta.data<-bulkref@meta.data%>%
  mutate(sublabel=str_remove_all(label," \\(.+|Early ")%>%
           str_replace("emmo","emo"))%>%
  mutate(sublabel=case_when(str_detect(label,
                                       "EnEp|MUC5B|SOX9|IHH|Cili|Gland|KRT|Meso")~"Epithelial",
                            str_detect(label,"EnS")~"Mesenchymal cells",
                            str_detect(label,"Th")~"CD4 T-cells",
                            TRUE~sublabel))

bulkquery<-AggregateExpression(inte,group.by = "ct",
                               return.seurat = T,features = rownames(bulkref))
bulkquery<-ScaleData(bulkquery,assay = "RNA",features = rownames(inte))
res <- SingleR(test=bulkquery@assays$RNA$scale.data,#this
               ref=bulkref@assays$SCT$data, 
               labels=bulkref@meta.data$sublabel, method = "cosine",
               quantile = 0.999,tune.thresh = .1)
res<-as.data.frame(res)%>%rownames_to_column("ct")
res<-res%>%mutate(pruned.labels=str_replace_na(pruned.labels,"unknown"))
temp<-res%>%mutate(ct=str_replace(ct,"-","_"))%>%select(ct,pruned.labels)%>%right_join(temp)
temp<-temp[order(match(temp$cell,colnames(inte))),]
inte<-AddMetaData(inte,metadata = temp,col.name = "pruned.labels")
inte@meta.data<-inte@meta.data%>%mutate(temp=paste(ct,':',pruned.labels))
temp%>%data.table::fwrite("/media/Lawrenson_Lab_NAS/uthscsa/group_data/Xenium_labels/pembro/Banksy_matrix/prote_l0.2_labels.gz")
```

```{r}
cellcols<-c(Epithelial="#F29022","CD4 T-cells"="#18ABB8","Smooth muscle cells"="#AD6D5E",
            "B-cells"="#C8DD34","Macrophages M1"="#F781BF","Macrophages M2"="#F47494",
        "C7-Fibro"="#204175","C7-Activated-Fibro"="#536D9E","Fibro"="#4385BF",
        "Endothelial cells"="#E41A1C","Effector CD8 T-cells"="#8FC9BF",
        "Plasmablast/Plasma cells"="gold","Gamma-Delta T-cells" ="#910241")
```

# Subcluster flagged groups > 100 cells
```{r}
temp<-inte@meta.data%>%dplyr::count(pruned.labels)%>%arrange(n)
i<-temp%>%filter(n>100&str_detect(pruned.labels,"Eff|^Fib|Gamm|Mac"))%>%
  distinct(pruned.labels)%>%unlist()
tofix<-lapply(i,function(x) subset(inte,subset = pruned.labels==x))
names(tofix)<-i

tofix<-lapply(tofix,function(x) RunPCA(x,npcs=10,features=rownames(inte)))
tofix<-lapply(tofix,function(x) harmony::RunHarmony(x,group.by.vars="Section"))
tofix<-lapply(tofix,function(x) RunUMAP(x,reduction = "harmony",dims=1:10))
tofix<-lapply(tofix,function(x) FindNeighbors(x,k.param = 15,reduction = "harmony"))
tofix<-lapply(tofix,function(x) FindClusters(x,algorithm=4,resolution=.1))
res <- lapply(tofix,function(x)
  SingleR(test=x@assays$RNA$scale.data,#this
          clusters=x$seurat_clusters,
          ref=bulkref@assays$SCT$data, 
          labels=bulkref@meta.data$sublabel, method = "cosine",
               quantile = 0.999,tune.thresh = .1))
res<-lapply(res,as.data.frame)
res<-lapply(names(res),function(x) 
  res[[x]]%>%rownames_to_column("seurat_clusters")%>%
    mutate(newlabel=pruned.labels,
           pruned.labels=x)%>%
    select(seurat_clusters,newlabel,pruned.labels))%>%bind_rows()
temp<-lapply(tofix,function(x) x@meta.data)%>%bind_rows()
temp<-temp%>%rownames_to_column("cell")%>%
  select(cell,seurat_clusters,pruned.labels)%>%
  left_join(res,by=c("pruned.labels","seurat_clusters"))
temp<-inte@meta.data%>%select(pruned.labels)%>%
  rownames_to_column("cell")%>%left_join(temp%>%
                                           select(cell,newlabel),by="cell")
#manually fix small set that make no sense
temp<-temp%>%mutate(newlabel=ifelse(is.na(newlabel),
                                    pruned.labels,newlabel))
temp<-temp%>%mutate(newlabel=ifelse(pruned.labels%in%
                                      c("Gamma-Delta T-cells","C7-Activated-Fibro"),
                                    paste0(newlabel," to discard"),newlabel))
inte<-AddMetaData(inte,metadata = temp,col.name = "newlabel")

```

# Manually fix groups following Marcela's observations 
```{r}
i<-c("CD4 T-cells","Macrophages M1","Effector CD8 T-cells","C7-Fibro")
tofix<-lapply(i,function(x) subset(inte,subset = newlabel==x))
names(tofix)<-i

tofix<-lapply(tofix,function(x) RunPCA(x,npcs=10,features=rownames(inte)))
tofix<-lapply(tofix,function(x) harmony::RunHarmony(x,group.by.vars="Section"))
tofix<-lapply(tofix,function(x) RunUMAP(x,reduction = "harmony",dims=1:10))
tofix<-lapply(tofix,function(x) FindNeighbors(x,k.param = 15,reduction = "harmony"))
tofix<-lapply(tofix,function(x) FindClusters(x,algorithm=4,resolution=.1))
tofix$`Effector CD8 T-cells`<-FindClusters(tofix$`Effector CD8 T-cells`,resolution = .5,algorithm = 4)
tofix$`C7-Fibro`<-FindClusters(tofix$`C7-Fibro`,resolution = .5,algorithm = 4)
res <- lapply(tofix,function(x)
  SingleR(test=x@assays$RNA$scale.data,#this
          clusters=x$seurat_clusters,
          ref=bulkref@assays$SCT$data, 
          labels=bulkref@meta.data$sublabel, method = "cosine",
               quantile = 0.999,tune.thresh = .1))
res<-lapply(res,as.data.frame)
#after inspection we don't agree with this labels
#kept CD4 and effector CD8 grouped
#and manually label M1 and C7 subclusters

i<-tofix$`C7-Fibro`@meta.data%>%select(seurat_clusters)%>%rownames_to_column("cell")%>%
  mutate(c7_cl=seurat_clusters)%>%select(-seurat_clusters)
temp<-inte@meta.data%>%rownames_to_column("cell")%>%left_join(i)
temp<-temp%>%mutate(c7_cl=ifelse(is.na(c7_cl),newlabel,c7_cl))
inte<-AddMetaData(inte,metadata = temp,col.name = "c7_cl")

i<-tofix$`Macrophages M1`@meta.data%>%select(seurat_clusters)%>%rownames_to_column("cell")%>%
  mutate(m1_cl=seurat_clusters)%>%select(-seurat_clusters)
temp<-inte@meta.data%>%rownames_to_column("cell")%>%left_join(i)
temp<-temp%>%mutate(m1_cl=ifelse(is.na(m1_cl),newlabel,m1_cl))
inte<-AddMetaData(inte,metadata = temp,col.name = "m1_cl")
temp<-inte@meta.data%>%select(ct,pruned.labels,newlabel,m1_cl,c7_cl)%>%
  rownames_to_column("cell")
temp%>%data.table::fwrite("/media/Lawrenson_Lab_NAS/uthscsa/group_data/Xenium_labels/pembro/Banksy_matrix/prote_l0.2_labels.gz")
```