---
  title: "domains"
---
  
```{r}
library(tidyverse)
library(Seurat)
library(dbscan)
library(clusterProfiler)
library(limma)
library(speckle)

cols<-c("#E41A1C","#536D9E","#459E6E","cornflowerblue","gold","#F29022","#F781BF","#C598C9",
        "#AD6D5E","#7D8285","#4385BF","#204175","#1B9E77","#98D486","#D2C92D","#EFAC4C",
        "#F47494","#D8227D","#910241","#18ABB8","#6ECDDC","#f46d43","#A82676","#655D9B",
        "#8CA77B","#17542A","#94A908","#C8DD34","#8FC9BF","white")

meta<-data.table::fread("/media/Lawrenson_Lab_NAS/uthscsa/group_data/Xenium_labels/pembro/Banksy_domains.gz")

meta<-meta%>%add_count(circle)%>%filter(n>500)
names(cols)<-sort(unique(meta$Core_ID))

meta%>%ggplot(aes(x=-x_centroid,y=-y_centroid,col=as.factor(res.0.5)))+
  geom_point(size=.1)+
  geom_text(data=meta%>%group_by(circle,StudyID)%>%
              summarise(x_centroid=median(x_centroid),y_centroid=median(y_centroid)),
            aes(label=StudyID),size=2.5,col="black")+
  scale_color_manual(values=cols)+theme(legend.position = "n")
```

# Composition contrast
```{r}
annot<-read_tsv("/media/Lawrenson_Lab_NAS/uthscsa/group_data/Xenium_labels/pembro/PEmbro_TMA_deidentified.tsv")
meta<-meta%>%mutate(Core_ID=as.numeric(Core_ID))%>%left_join(annot,by=c("Core_ID"="Core ID"))

temp<-meta%>%distinct(circle,res.0.5)%>%count(res.0.5,name = "circles")
temp<-meta%>%distinct(Core_ID,res.0.5)%>%count(res.0.5,name = "cores")%>%right_join(temp)
temp<-meta%>%distinct(StudyID,res.0.5)%>%count(res.0.5,name = "studies")%>%right_join(temp)
temp<-meta%>%count(res.0.5,name = "cells")%>%right_join(temp)
p0<-temp%>%pivot_longer(-1,names_to = "unit",values_to = "n")%>%
    ggplot(aes(x=n,y=as.factor(res.0.5),fill=as.factor(res.0.5)))+
    geom_col()+geom_text(aes(label=n))+
    facet_grid(~unit,scales="free_x")+
    scale_fill_manual(values=cols)+theme(legend.position = "n")+scale_x_sqrt()

meta<-meta%>%mutate(Gr=ifelse(responder==T,"responder","non_responder"))
props<-getTransformedProps(meta$res.0.5,
                           meta$StudyID)
ids<-meta%>%distinct(Gr,StudyID)
designM<-model.matrix(~0+Gr,data=ids)#but Cores are not independent 

props<-props$TransformedProps[,ids$StudyID]
fit<-lmFit(props,designM)
cont<-makeContrasts(Grresponder-Grnon_responder,levels = designM)
fit<-contrasts.fit(fit,cont)
fit <- eBayes(fit, robust=TRUE)
res<-topTable(fit,number = nrow(props),coef = 1)
i<-res%>%filter(abs(logFC)>1)%>%rownames()

p1<-res%>%rownames_to_column("Domain")%>%arrange(logFC)%>%
  mutate(Domain=factor(Domain,levels=Domain))%>%
  ggplot(aes(x=logFC,y=Domain,size=P.Value,col=logFC))+geom_point()+
  scale_color_gradient2(low="#2166ac", mid = "#f7f7f7", high = "#b2182b")+
  scale_size(range = c(5,1),trans="log10")+theme_minimal()+
  ggtitle("Responde - non-responder, proportions by StudyID")

temp<-meta%>%count(res.0.5,responder)%>%mutate(res.0.5=factor(res.0.5))
temp<-temp%>%group_by(responder)%>%summarise(n=sum(n),res.0.5="Total")%>%bind_rows(temp)
p2<-temp%>%mutate(res.0.5=factor(res.0.5,levels=c(levels(p1$data$Domain),"Total")))%>%
  ggplot(aes(x=n,y=res.0.5,fill=responder))+
  geom_bar(stat="identity",position="fill")+
  geom_vline(xintercept = .5)+labs(x="Cell prop")

```

# Cell type markers
```{r}
files<-list.files("/media/Xenium_On_NAS/xenium_reanalysis",full.names = T)
files<-files[str_detect(files,"Pro")]
files<-files[str_detect(files,"UTP",negate=T)]
xenium.list<-lapply(files, function(x) Read10X_h5(paste0(x,"/outs/cell_feature_matrix.h5")))
names(xenium.list)<-str_remove(files,".+sis.")

inte<-lapply(xenium.list, CreateSeuratObject)
inte<-merge(inte[[1]],y = inte[names(inte)[-1]],
            add.cell.ids =names(inte))
inte<-NormalizeData(inte)
inte<-subset(inte,cells=meta$cell_id)
inte<-AddMetaData(inte,metadata = meta%>%column_to_rownames("cell_id"))

j<-c("KIT","TPSAB1","SIGLEC8","PTPRC","CD79A","BANK1","MS4A1",
     "CD27","CD38","BCL6","CXCR5","MME","JCHAIN","PRDM1","SDC1",
     "IGHA1","IGHG1","IGHG2","IGHG3","IGHG4","IGHM","NCAM1","FCGR3A",
     "CD3D","TRDC","TRGC1","TRGC2","CD4","IL4","GATA3","CCR4","CXCR4",
     "RORC","IL17A","STAT3","CCR6","FOXP3","IL2RA","CD8A","SELL",
     "CCR7","CD44","IL7R","CD69","CTLA4","LAG3","PDCD1","TIGIT","HAVCR2",
     "TOX","CD1C","HLA-DRA","HLA-DPA1","ITGAM","CD68","CXCL10","CCL2",
     "NOS2","ARG1","CD163","IL10","EPCAM","KRT10","KRT18","KRT8","WT1",
     "MUC5B","SOX9","SPDEF","LGR5",
     "PAX8","ESR1","FOXJ1","PAEP","PECAM1","PGR","IGF1","MMP11","FOXO1",
     "DCN","PDGFRA","THY1","COL1A1","ACTA2","TAGLN","MYL9","FAP","C7","GAS5")
DotPlot(subset(inte,subset = res.0.5%in%i),features = j,group.by = "res.0.5")+
  RotatedAxis()+scale_color_gradient2(low="#2166ac", mid = "#f7f7f7", high = "#b2182b")+
  theme(axis.text.x = element_text(size=8))
k<-tail(rownames(inte),20)
DotPlot(subset(inte,subset = res.0.5%in%i),features = k,group.by = "res.0.5")+
  coord_flip()+scale_color_gradient2(low="#2166ac", mid = "#f7f7f7", high = "#b2182b")+
  theme(axis.text.x = element_text(size=8))


```

# Domain markers
```{r}
inte<-lapply(xenium.list,function(x) x$`Gene Expression`)
inte<-lapply(inte, CreateSeuratObject)
inte<-merge(inte[[1]],y = inte[names(inte)[-1]],
            add.cell.ids =names(inte))
inte<-AddMetaData(inte,metadata = meta%>%column_to_rownames("cell_id"))
i<-rownames(inte)
i<-i[str_detect(i,"fung|bact",negate = T)]
inte<-subset(inte,features=i)
inte<-NormalizeData(inte)

pb<-AggregateExpression(inte,group.by = c("Gr","Core_ID","res.0.5"),return.seurat = T)
domDEG<-FindAllMarkers(pb,group.by = "res.0.5",#latent.vars = "StudyID",
                       test.use = "DESeq2",min.cells.group = 2)
k<-domDEG%>%filter(p_val_adj<0.05&avg_log2FC>log2(1.5)&!gene%in%j&cluster%in%i)%>%
  distinct(gene)%>%unlist()
domDEG%>%filter(gene%in%k&cluster%in%i)%>%
  mutate(cluster=factor(cluster,levels=1:19))%>%
  ggplot(aes(x=cluster,y=gene,col=avg_log2FC,size=p_val_adj))+
  geom_point()+
  scale_color_gradient2(low="#2166ac", mid = "#f7f7f7", high = "#b2182b")+
  scale_size(range = c(5,1),trans="sqrt",breaks = c(1e-23,1e-13,1e-3,1))+
  theme_minimal()

```

# Group markers per domain
```{r}
pb<-AggregateExpression(inte,group.by = c("res.0.5"),return.seurat = T)
mat<-pb@assays$RNA$scale.data

dom5k<-data.table::fread("/media/Lawrenson_Lab_NAS/uthscsa/group_data/Xenium_labels/pembro/Banksy_domains5k.gz")
dom5k<-dom5k%>%add_count(circle)%>%filter(n>500)
files<-list.files("/media/Xenium_On_NAS/xenium_reanalysis",full.names = T)
files<-files[str_detect(files,"TMA")]
files<-files[str_detect(files,"UTP|Pro",negate=T)]
xenium.listA<-lapply(files, function(x) Read10X_h5(paste0(x,"/outs/cell_feature_matrix.h5")))
names(xenium.listA)<-str_remove(files,".+sis.")
inte5k<-lapply(xenium.listA,function(x) x$`Gene Expression`)
inte5k<-lapply(inte5k, CreateSeuratObject)
inte5k<-merge(inte5k[[1]],y = inte5k[names(inte5k)[-1]],
            add.cell.ids =names(inte5k))
inte5k<-subset(inte5k,cells=dom5k$cell_id)
inte5k<-AddMetaData(inte5k,metadata = dom5k%>%column_to_rownames("cell_id"))
inte5k<-NormalizeData(inte5k)
pb<-AggregateExpression(inte5k,group.by = c("res.0.5"),return.seurat = T)
mat5k<-pb@assays$RNA$scale.data

i<-rownames(mat5k)
i<-i[i%in%rownames(mat)]
colnames(mat5k)<-paste0("5k_",colnames(mat5k))
temp<-cor(concate,method = "spearman")
temp<-temp[str_detect(rownames(temp),"target"),str_detect(rownames(temp),"5k")]
matches<-rownames(temp)[apply(temp,2,which.max)]
matches[apply(temp,2,max)<0.5]<-"no"

names(cols)<-unique(c(colnames(concate)[1:19],matches))
Heatmap(t(concate),name="z_aggr",column_names_gp = gpar(fontsize=6),
        left_annotation = rowAnnotation(panel=ifelse(str_detect(colnames(concate),"5k"),
                                                     "5k","targeted"),
                                        gr=c(colnames(concate)[1:19],matches),
                          col=list(gr=cols,panel=c("5k"="#C8DD34","targeted"="gold"))),
        row_split = c(colnames(concate)[1:19],matches),row_title = NULL)
```

# 5k enrichment
```{r}
matches<-as.data.frame(cbind(targeted_domain=matches,
                             domain_5k=str_remove(colnames(temp),"5k_")))
temp<-inte5k@meta.data%>%rownames_to_column("cell")%>%
  mutate(res.0.5=as.character(res.0.5))%>%select(cell,res.0.5)%>%
  inner_join(matches,by=c("res.0.5"="domain_5k"))
inte5k<-AddMetaData(inte5k,metadata = temp,col.name = "targeted_domain")

pb<-AggregateExpression(inte5k,group.by = c("circle","targeted_domain"),return.seurat = T)
i<-rowSums(pb@assays$RNA$counts)
i<-i[i>quantile(i,0.05)]
pb<-subset(pb,subset=targeted_domain!="no",features = names(i))
domDEG<-FindAllMarkers(pb,group.by = "targeted_domain",
                       min.cells.group = 2,logfc.threshold = 0)
# CD274 is not significant
domDEG%>%filter(avg_log2FC>log2(1.5))%>%write_csv("/media/Lawrenson_Lab_NAS/uthscsa/group_data/Xenium_labels/5k_matcheDomains_DEG.csv")

pb<-AggregateExpression(inte5k,group.by = c("targeted_domain"),return.seurat = T)
pb<-subset(pb,subset=targeted_domain!="no")
mat<-pb@assays$RNA$scale.data
mat<-mat%>%as.data.frame()%>%rownames_to_column("gene")%>%
  pivot_longer(-1,names_to = "cluster",values_to = "z")%>%
  arrange(desc(z))
ranks<-mat%>%split(f = mat$cluster)%>%lapply(function(x) 
  x%>%select(gene,z)%>%deframe)
gsea_bp<-lapply(ranks,function(x)
  gseGO(x,OrgDb = 'org.Hs.eg.db',seed = T,
        pvalueCutoff = 0.05,ont = "BP",keyType = "SYMBOL",
        pAdjustMethod = "fdr"))
gsea_bp<-lapply(gsea_bp,simplify)
gsea_bp<-lapply(names(gsea_bp),function(x) 
  as.data.frame(gsea_bp[[x]])%>%mutate(cluster=x))%>%bind_rows()
k<-gsea_bp%>%mutate(status=ifelse(NES>0,"Up","Down"))%>%
    group_by(cluster,status)%>%
    slice_max(setSize)%>%slice_max(abs(NES))%>%
    distinct(Description)%>%unlist()
gsea_bp%>%filter(Description%in%k)%>%
    ggplot(aes(x=cluster,y=Description,col=NES,size=p.adjust))+
    geom_point()+scale_color_gradient2(low="#2166ac", mid = "#f7f7f7", high = "#b2182b")+
    scale_size(range = c(5,1),trans="log10")+theme_minimal()+labs(x="Domain")+
  theme(axis.text.x = element_text(angle=45,vjust = 1,hjust = 1))

```

# Spatial plots
```{r}